CREATE TABLE `cnblogs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `title` VARCHAR(500) DEFAULT NULL COMMENT '文章标题',
  `url` VARCHAR(500) DEFAULT NULL COMMENT '文章详情地址',
  `short` VARCHAR(1000) DEFAULT NULL COMMENT '文章简介',
  `author` VARCHAR(100) DEFAULT NULL COMMENT '博主',
  `author_url` VARCHAR(500) DEFAULT NULL COMMENT '博主主页链接',
  `create_time` DATETIME NOT NULL COMMENT '发布时间',
  `comment_counts` INT(11) NOT NULL COMMENT '评论数',
  `read_counts` INT(11) NOT NULL COMMENT '阅读量',
  `insert_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=1661 DEFAULT CHARSET=utf8mb4